In [2]:
#Demo Example to build our model

# Cosine_Similarity

In [8]:
text = ["London Paris London","Paris London Paris"] 

In [4]:
# import the sklearn to count the frequecy in text
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
# CountVectorizer is class having method to count frequeny
cv =  CountVectorizer()

In [9]:
# using methods fit_transforms to find the frequency 
count_matrix = cv.fit_transform(text)


In [11]:
count_matrix.toarray()

array([[2, 1],
       [1, 2]], dtype=int64)

In [12]:
#import the sklearn to cosine_similarity between two vectors
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
similarity_score = cosine_similarity(count_matrix)
similarity_score

array([[1. , 0.8],
       [0.8, 1. ]])

In [17]:
pwd

'C:\\Users\\Virender Pal Singh'

In [23]:
cd C:\\Users\\Virender Pal Singh\\Desktop\\Document\\machine_learing\\

C:\Users\Virender Pal Singh\Desktop\Document\machine_learing


In [24]:
pwd

'C:\\Users\\Virender Pal Singh\\Desktop\\Document\\machine_learing'

In [25]:
# Alogrithm for recomndation system

#step 1: Read csv file
#step 2: selection Features
#step 3: Create the column in df which combine all selection features
#step 4: create count_matrix for this new combined columns
#step 3: Compute the cosine_similarity based upon the coulum matrix



In [26]:
import pandas as pd
import numpy as np


In [28]:
# step 1
data = pd.read_csv("C:\\Users\\Virender Pal Singh\\Desktop\\Document\\machine_learing\\movie_dataset.csv")

In [29]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

         ...         runtime  \
0        ...           162.0   
1        ...           169.0   
2        ...           148.0   
3        ...           165.0   
4        ...           132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5

In [30]:
# step 2 
# selection featurs
features = ['keywords', 'cast', 'genres', 'director']

In [34]:
# step 3

for feature in features:
    data[feature] = data[feature].fillna('')
def combine_features(row):
    try:
        return row['keywords'] + " " + row['cast'] + " " + row["genres"] + " " + row["director"]
    except:
        print("Error:", row)
data["combine_features"] = data.apply(combine_features, axis=1)
print("Combined Features:", data["combine_features"].head())

Combined Features: 0    culture clash future space war space colony so...
1    ocean drug abuse exotic island east india trad...
2    spy based on novel secret agent sequel mi6 Dan...
3    dc comics crime fighter terrorist secret ident...
4    based on novel mars medallion space travel pri...
Name: combine_features, dtype: object


In [35]:
# step 4
cv = CountVectorizer()
count_matrix = cv.fit_transform(data["combine_features"])
count_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
# step 5

cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1.        , 0.10540926, 0.12038585, ..., 0.        , 0.        ,
        0.        ],
       [0.10540926, 1.        , 0.0761387 , ..., 0.03651484, 0.        ,
        0.        ],
       [0.12038585, 0.0761387 , 1.        , ..., 0.        , 0.11145564,
        0.        ],
       ...,
       [0.        , 0.03651484, 0.        , ..., 1.        , 0.        ,
        0.04264014],
       [0.        , 0.        , 0.11145564, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04264014, 0.        ,
        1.        ]])

In [37]:
# helper function 

def get_title_from_index(index):
    return data[data.index == index]["title"].values[0]

In [38]:
def get_index_from_title(title):
    return data[data.title == title]["index"].values[0]

In [39]:
movie_user_like = "The Dark Knight Rises"

In [40]:
# step 6
# Get index of this movie from its title
movie_index =  get_index_from_title(movie_user_like)
movie_index

3

In [41]:
similar_movies = list(enumerate(cosine_sim[movie_index]))
similar_movies

[(0, 0.03774256780481986),
 (1, 0.03580574370197164),
 (2, 0.16357216402190616),
 (3, 0.9999999999999997),
 (4, 0.03922322702763681),
 (5, 0.07844645405527362),
 (6, 0.0),
 (7, 0.03580574370197164),
 (8, 0.08362420100070908),
 (9, 0.12009611535381537),
 (10, 0.11766968108291043),
 (11, 0.23533936216582085),
 (12, 0.04089304100547654),
 (13, 0.03922322702763681),
 (14, 0.14824986333222023),
 (15, 0.0),
 (16, 0.03522349768381735),
 (17, 0.04181210050035454),
 (18, 0.07161148740394328),
 (19, 0.04181210050035454),
 (20, 0.04003203845127179),
 (21, 0.04003203845127179),
 (22, 0.0),
 (23, 0.0),
 (24, 0.06933752452815364),
 (25, 0.08770580193070293),
 (26, 0.03706246583305506),
 (27, 0.08006407690254358),
 (28, 0.08006407690254358),
 (29, 0.1254363015010636),
 (30, 0.07692307692307693),
 (31, 0.07844645405527362),
 (32, 0.07412493166611012),
 (33, 0.07412493166611012),
 (34, 0.0),
 (35, 0.08559209850218259),
 (36, 0.08006407690254358),
 (37, 0.0),
 (38, 0.038461538461538464),
 (39, 0.1153846

In [43]:
# step 7
# sorted the movie in descending order
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1],reverse = True)
sorted_similar_movies

[(3, 0.9999999999999997),
 (119, 0.7307692307692306),
 (65, 0.6923076923076922),
 (4638, 0.45291081365783836),
 (2793, 0.39467610868816316),
 (1196, 0.37630890450319093),
 (428, 0.3602883460614461),
 (1359, 0.3530090432487313),
 (210, 0.3396831102433788),
 (1720, 0.3335621924974955),
 (2371, 0.3335621924974955),
 (1740, 0.32776066832815337),
 (3332, 0.3149448894660932),
 (3359, 0.29417420270727607),
 (3819, 0.2926847035024818),
 (3966, 0.2926847035024818),
 (4099, 0.29268470350248177),
 (2790, 0.29134281629169184),
 (1013, 0.28625128703833574),
 (1792, 0.28625128703833574),
 (2398, 0.28625128703833574),
 (1503, 0.2853908964926965),
 (3293, 0.28022426915890253),
 (1986, 0.27735009811261463),
 (4664, 0.27735009811261463),
 (1234, 0.27456258919345766),
 (3073, 0.2692307692307693),
 (95, 0.264197974633739),
 (813, 0.264197974633739),
 (1664, 0.264197974633739),
 (968, 0.2631174057921088),
 (1674, 0.2631174057921088),
 (1727, 0.2631174057921088),
 (1803, 0.2631174057921088),
 (3637, 0.26311

In [44]:
# step 8 :Print titles of first 50 movies
i = 0
for movie in sorted_similar_movies:
    print(get_title_from_index(movie[0]))
    i = i + 1
    if i > 50:
        break
        

The Dark Knight Rises
Batman Begins
The Dark Knight
Amidst the Devil's Wings
The Killer Inside Me
The Prestige
Batman Returns
Batman
Batman & Robin
Kick-Ass
RockNRolla
Kick-Ass 2
Harry Brown
In Too Deep
Defendor
Point Blank
Harsh Times
True Romance
Child 44
Pain & Gain
Hitman
Takers
10th & Wolf
Faster
Bronson
The Art of War
Romeo Is Bleeding
Interstellar
Superman
Dead Man Down
Murder by Numbers
Wild Card
3 Days to Kill
Blood and Wine
Kill the Messenger
Mi America
Man on Fire
The Bone Collector
Half Past Dead
Legend
The Protector
Rampage
Code of Honor
Jack Reacher
Law Abiding Citizen
Patriot Games
Vantage Point
Smilla's Sense of Snow
The Newton Boys
The Skulls
The Betrayed
